set(headers ${headers}
	src/PCH.h
    src/log.h
    src/util.h
    src/hook.h
    src/settings.h
    src/Config.h
    src/InputManager.h
    src/higgsinterface001.h
    src/ShackleModeManager.h
    src/ClimbManager.h
    src/ClimbSurfaceDetector.h
    src/BallisticController.h
    src/CriticalStrikeManager.h
    src/StaminaDrainManager.h
    src/ClimbingDamageManager.h
    src/EquipmentManager.h
    src/HiggsCompatManager.h
    src/ClimbExitCorrector.h
    src/AudioManager.h
    src/HavokUtils.h
    src/util/VRNodes.h
    src/util/Raycast.h
    external/PapyrusVRAPI.h
    external/VRManagerAPI.h
    external/PapyrusVRTypes.h
    external/VRHookAPI.h
)